version: "3.8"

services:
  db:
    container_name: db
    image: mysql:latest
    build:
      context: ./database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db-data:/var/lib/mysql/
      - ./database/db.sql:/sql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio
  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on: 
      - frontend
      - api
      - auth
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./client
    depends_on:
      - auth
      - api
    ports:
      - 8080:80
    restart: always
  api:
    container_name: api
    image: api
    build:
      context: ./api
    depends_on: 
      - db
      - auth
    ports:
      - 8081:8081
    restart: always
    command: npm start
  auth:
    container_name: auth
    image: auth
    build:
      context: ./auth
    depends_on: 
      - db
    ports: 
      - 8082:8082
    restart: always
    command: npm start
  images:
    container_name: images
    image: images
    build:
      context: ./images
    ports:
      - 8083:8083
    restart: always
    command: npm start
volumes:
  db-data:
    